### ISSUE TITLE
ESRI Angular with PointDrawAction

### ISSUE THREAD

**Issue by Meeett** [Esri/angular-cli-esri-map#31]
Hallo,
I added an Question on GeoNet too(https://community.esri.com/thread/234376-esri-angular-with-pointdrawaction)

I tried to setup ESRI JS API with Angular, but I was not able to implement "PointDrawAction".
For a better troubleshooting I setup this Repository: https://github.com/Meeett/PointDrawActionLag
For PontDrawAction I used: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-draw-PointDrawAction.html

It seems that ESRI JS API is not well supported to use it with angular?

If anybody could find a solution it would be awesome!

**Comment by andygup** [comment]
@Meeett 

>> I tried to setup ESRI JS API with Angular, but I was not able to implement "PointDrawAction".

`PointDrawAction` seems to be working. Other than the drag performance issue was there something else not working? In the code comments you mention `esri.Graphic` doesn't work, that's because it's an interface and you need a reference to an actual instance of `Graphic`.

We were are able to repro the drag-delay issue in a plain old JS app, so this is an ArcGIS JS API issue and it's unrelated to Angular. We'll investigate it further and see what fixes are needed. Thanks for the heads up!

Repro sample: https://codepen.io/andygup/pen/jopvgG?editors=1000

Stackblitz sample: https://angular-cli-esri-map2-fyypnq.stackblitz.io/.
