### ISSUE TITLE
Upgrade to 4.12 fails in IE11

### ISSUE THREAD

**Issue by kelylah** [Esri/angular-cli-esri-map#94]
Hi,
I'm updating production application from version 4.11 to 4.12 (target is 4.17). I encountered an error in IE11. FF and Edge on chromium work correctly.
This application is quite complicated and related to the internal resources of the company, so I prepared a simple one based on the sample application provided by you. It's in this repository:
[https://github.com/kelylah/arcgis-ng](https://github.com/kelylah/arcgis-ng)
Master branch is with ArcGIS JS API 4.12 version when 'arcgis411' is with version 4.11.
I tried to make dependencies as similar as possible to the production application. Dependencies aren't the newest one.
It is ejected and has custom webpack configuration.
The error that appears in IE11 console is: Object expected, zone.js (240,1) in Zone.prototype.scheduleTask

As we settle with TJ from Esri Customer Care the breaking change between 4.11 and 4.12 was using Fetch API despite esri/request:
`esri/request now uses the Fetch API internally to request resources. When not available (e.g. with IE11), we use a fetch polyfill instead.`
[https://developers.arcgis.com/javascript/latest/breaking-changes/#412](https://developers.arcgis.com/javascript/latest/breaking-changes/#412)

This issue looks similar to issue #43 
Looking forward to any clues.

Adam

**Comment by andygup** [comment]
Hi Adam, I don't have access to IE 11. Does this sample work in IE 11 when you change the version to 4.12?  https://developers.arcgis.com/javascript/latest/sample-code/request/

**Comment by kelylah** [comment]
Hi Andy,
Thanks for your response. Yes, this sample is working in IE11.
I believe that problem isn't the JS API itself but a special coincidence of JS API with Angular stuff.

**Comment by andygup** [comment]
Thanks. I do have a few suggestions that you can try:
* Make sure all the IE polyfills are enabled in Angular
* There's a possibility that webpack causing the problem, since this doesn't show up in a plain old JavaScript sample. You might look to see if `AngularCompilerPlugin` has an `compiler` options related to optimization that you can temporarily disable to see if that fixes the problem. https://github.com/kelylah/arcgis-ng/blob/master/webpack.config.js#L488
* Consider upgrading your version of Angular. Angular 7 is [no longer supported](https://angular.io/guide/releases) by Google. It's possible that this old version of Angular doesn't have the necessary configuration options to allow you to bypass the issue.
* Try testing using `esri-loader` instead of using `arcgis-webpack-plugin`. That will let you bypass an compile-time problems.

**Comment by kelylah** [comment]
Hi Andy, Hi Guys,
I'm coming back with this topic. A colleague of mine has updated Angular to 10.2.3 and we are simultaneously trying to build this app.
I'm trying with arcgis-webpack-plugin as it allows to make 'normal' imports opposite to esri-loader.
It looks like my configuration doesn't read esriConfig. I put it in 2 places.
1. In starting index.ejs file as global
2. In main.ts (after importing from 'esri/config' - underlined as error)
Both files attached in ZIP.
I also attached a screenshot of the build of the app that shows that dojo.js is searched in node_modules
[esriConfigs.zip](https://github.com/Esri/angular-cli-esri-map/files/6164326/esriConfigs.zip)
How can I be assured that esriConfig is set properly? 
Is there any other place where I can insert this esriConfig setting?

I appreciate any help.
Adam

**Comment by andygup** [comment]
Maybe try using our new ES modules build => `npm i @arcgis/core`. The next release, 4.19, will be available in early April and you can also try it out at `npm i @arcgis/core@next`. 

Here are some samples, starting at 4.19 (and also when you install @next version) you won't need to configure the assets as mentioned in the README:

https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli

**Comment by kelylah** [comment]
With pleasure but well, you know... IE11!
That's why we are trying to run with JS API 4.17.

**Comment by andygup** [comment]
Closing. @kelylah if you have additional questions let us know.
