### ISSUE TITLE
NgRx effects with QueryTask

### ISSUE THREAD

**Issue by forrestlin100** [Esri/angular-cli-esri-map#97]
Anyone know how to do QueryTask with NgRx effects?

I did something like this, but doesn't work.

// esri-map.action.ts
export const query = createAction(
    '[Esei Map] Query Task',
    props<{url: string, query: Query }>()
  );
export const querySuccess = createAction(
    '[Esei Map] Query Success',
    props<{ featureSet: FeatureSet }>()
  );
export const queryFailure = createAction(
    '[Esei Map] Query Fail',
    props<{ error: string }>()
  );

//esri-map.service.ts
@Injectable()
export class EsriMapService {
  constructor() { }
  query(url: string, query: Query): Observable<FeatureSet> {
    const queryTask = new QueryTask({ url: url });
    return from(queryTask.execute(query)).pipe(
      tap(data => console.log('QueryTask: ' + JSON.stringify(data))),
      catchError(this.handleError)
    );
  }
}

//esri-map.effect.ts
@Injectable()
export class EsriMapEffect {
  constructor(private actions$: Actions, private esriMapService: EsriMapService) { }
  query$ = createEffect(() => {
    return this.actions$
      .pipe(
        ofType(EsriMapAction.query),
        switchMap(action =>
          this.esriMapService.query(action.url, action.query)
            .pipe(
              map(featureSet => EsriMapAction.querySuccess({ featureSet })),
              catchError(error => of(EsriMapAction.queryFailure({ error })))
            )
        )
      );
  });
}

**Comment by epaitz** [comment]
Generally, I think what you have is correct. 

I would not handle the error in the service because you are trapping the error in the effect. If you trap the error in the service you will have to re-throw the error so that the catchError() can catch the error in the Effect and the return the EsriMapAction. So, don’t catch the error in the service. 

Also, I would not create specific QueryTask actions. I am not sure what you are trying to do other than calling the JSAPI QueryTaks but I would create actions like “open attribute table” and “close attribute table”. Here are some actions I was playing around with.

    export const AttributeTableOpen = createAction(MapActionTypes.AttributeTableOpen, props<{title: string, id: string}>());
    export const AttributeTableClose = createAction(MapActionTypes.AttributeTableClose, props<{id: string}>());
    export const AttributeTableSelect = createAction(MapActionTypes.AttributeTableSelect, props<{index: number}>());

I think I will have to pass the URL as an Action property but I am not sure yet. 

In a project I was working I am using the Angular Material tab control and each tab would have a data grid. So AttributeTableOpen would add a new tab to the tab control and then fetch the records. In my Effect I was planning on using a QueryService to fetch the FeatureSet from the server and then write the feature data into the state. 

I have not worked it all out yet because this might be tricky to implement with something like Ag-Grid but might be easier with the Angular Material Data Table. 

I will be one of the presenters for the 2021 Developer Summit giving the Angular presentation. We are going to show how to create a medium to large scale application using NgRx. Here is the project I created for the presentation.

https://github.com/epaitz/jsapi-angular-ngrx-ds2021

It does not have any QueryTask code, but it does leverage NgRx. Maybe it will help you get some ideas.

**Comment by andygup** [comment]
Closing. @forrestlin100 if you have more questions feel free to post then.
